SELECT UGU.USER_ID, UGU.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS UGU 
    JOIN USED_GOODS_BOARD AS UGB
    ON UGU.USER_ID = UGB.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE)

# SELECT *, SUM(PRICE)
# FROM USED_GOODS_BOARD
# WHERE WRITER_ID = 'dhfkzmf09'
# AND STATUS = 'DONE'
